"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    return await queryInterface.bulkInsert("kelas", [
      {
        id: 1,
        type: 1,
        nama: "7.1",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 2,
        type: 1,
        nama: "7.2",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 3,
        type: 1,
        nama: "7.3",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 4,
        type: 1,
        nama: "7.4",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 5,
        type: 1,
        nama: "7.5",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 6,
        type: 1,
        nama: "7.6",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 7,
        type: 1,
        nama: "7.7",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 8,
        type: 1,
        nama: "7.8",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 9,
        type: 1,
        nama: "7.9",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 10,
        type: 1,
        nama: "7.10",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 11,
        type: 1,
        nama: "7.11",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 12,
        type: 1,
        nama: "7.12",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 13,
        type: 2,
        nama: "8.1",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 14,
        type: 2,
        nama: "8.2",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 15,
        type: 2,
        nama: "8.3",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 16,
        type: 2,
        nama: "8.4",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 17,
        type: 2,
        nama: "8.5",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 18,
        type: 2,
        nama: "8.6",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 19,
        type: 2,
        nama: "8.7",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 20,
        type: 2,
        nama: "8.8",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 21,
        type: 2,
        nama: "8.9",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 22,
        type: 2,
        nama: "8.10",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 23,
        type: 2,
        nama: "8.11",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 24,
        type: 2,
        nama: "8.12",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 25,
        type: 3,
        nama: "9.1",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 26,
        type: 3,
        nama: "9.2",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 27,
        type: 3,
        nama: "9.3",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 28,
        type: 3,
        nama: "9.4",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 29,
        type: 3,
        nama: "9.5",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 30,
        type: 3,
        nama: "9.6",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 31,
        type: 3,
        nama: "9.7",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 32,
        type: 3,
        nama: "9.8",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 33,
        type: 3,
        nama: "9.9",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 34,
        type: 3,
        nama: "9.10",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 35,
        type: 3,
        nama: "9.11",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 36,
        type: 3,
        nama: "9.12",
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete("kelas", null, {});
  },
};
