"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    return await queryInterface.bulkInsert("mapel", [
      {
        id: 1,
        nama: "Matematika",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 2,
        nama: "Matematika",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 3,
        nama: "Matematika",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 4,
        nama: "Bahasa Indonesia",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 5,
        nama: "Bahasa Indonesia",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 6,
        nama: "Bahasa Indonesia",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 7,
        nama: "Bahasa Inggris",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 8,
        nama: "Bahasa Inggris",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 9,
        nama: "Bahasa Inggris",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 10,
        nama: "Pendidikan Agama Islam",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 11,
        nama: "Pendidikan Agama Islam",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 12,
        nama: "Pendidikan Agama Islam",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 13,
        nama: "Pendidikan Kewarganegaraan",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 14,
        nama: "Pendidikan Kewarganegaraan",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 15,
        nama: "Pendidikan Kewarganegaraan",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 16,
        nama: "Pendidikan Jasmani",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 17,
        nama: "Pendidikan Jasmani",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 18,
        nama: "Pendidikan Jasmani",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 19,
        nama: "Ilmu Pengetahuan Alam",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 20,
        nama: "Ilmu Pengetahuan Alam",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 21,
        nama: "Ilmu Pengetahuan Alam",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 22,
        nama: "Ilmu Pengetahuan Sosial",
        kelas: 1,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 23,
        nama: "Ilmu Pengetahuan Sosial",
        kelas: 2,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
      {
        id: 24,
        nama: "Ilmu Pengetahuan Sosial",
        kelas: 3,
        createdAt: new Date(),
        createdBy: 1,
        updatedAt: new Date(),
        updatedBy: 1,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete("mapel", null, {});
  },
};
